### ISSUE TITLE
Wiring diagram

### ISSUE THREAD

**Issue by omaranwar85** [PR-DC/PRDC_AD7797#1]
Hi,

Is it possible for you to share a rough wiring diagram of your circuit please?  I cant get any response from AD7797 and the ID returned is always 0.

Thanks

**Comment by mpetrasinovic** [comment]
@omaranwar85 We apologize for such late response, yes we will include an example.

**Comment by v-petrovic** [comment]
I've uploaded a schematic for one of our boards containing multiple AD7797 ICs, you can find it here:
https://github.com/PR-DC/PRDC_AD7797/blob/main/example_schematic.pdf

**Comment by omaranwar85** [comment]
Thank you very much.
RegardsOmar
Sent from Yahoo Mail on Android 
 
  On Mon, 19 Sep 2022 at 14:45, Veljko ***@***.***> wrote:   


Closed #1 as completed.
